dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
script:
- npm run build
deploy:
  provider: firebase
  token:
  - secure: dFxPYayQUuOphjglN7dnb4ahodmVSknh5LJthF7ASFX9vAV2/mEO5cu0mb4ppN7CcevjMKPehE6bJD3Dp/KigLPwUUNya+wgqMfY8gtJZqtw30XM8QD2JAw+rV/7AtJT/sqBUBah12uyV0gnhSUjDOQ4p6Dzln9uIXT39/v2ph8Kd4ACwo/ly6K/OImnfQRogpPHm4qRC6fvEQLB+G5oK8JKbHB+x5YqHjri5ffMgLeJRl6UE4krsq5qMY/6iDofEr80vWN77prNxSUjw6gsT3zLkexRYC7sXJ9IEfHDz7wCcJLpqtYwATvadP0NV4Cq6mADmIj1BHwcSCZqM10W7V/Ojs2O4R6zExQioPWC7VzoEcY1YqJrLOxQSzrHvCF8XoZD799NPD/m2F2CJqzdLP0JRaPfb0CJodbckWlScCOyNr88YUNP+PdymJ0EPitDODerjpbs1QOQPpgzKXHQ7oMMI9RjOCGaXNQfvSZWaQ2XP6wOwibPJdALAG/j8KvJa7gS6dqiqBvZPqtprl0j6QIBOSACs/uRdyhqY2dGuomtNL2WrD6+9nmeMxf+TA/RAIwiw1yGDtY261LDOpBHPzthHnWyzjAcmUTYbRmPGMgHnnFAuLqLlsQPvUcp2A1HwEvFEWv4lj6Kcp6q7R14UupdOS5XI75OiI5oO6p6CiU=
